sudo: required

language: python

python:
  - "3.6"

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

before_install:
  # Required to run browser tests (FF) ##
  - sudo ./setup_geckodriver.sh
  - export PATH="${HOME}/geckodriver:${PATH}"

install:
  - pip install -r requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 15 # give xvfb some time to start

script:
  - python manage.py test -v 2